apiVersion: v1
kind: Service
metadata:
    name: "smartsensors-ad33"
    labels:
        app: "smartsensors-ad33"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "smartsensors-ad33"
